# Generated by Django 2.1.2 on 2018-11-07 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('birthDate', models.DateField(default=datetime.date.today)),
                ('age', models.CharField(default='', max_length=2)),
                ('breed', models.CharField(default=0, max_length=30)),
                ('sickness', models.CharField(default=0, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='mypet',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
