# Generated by Django 2.1.2 on 2018-11-07 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20181107_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_time',
            field=models.CharField(default=5, max_length=4),
        ),
        migrations.AlterField(
            model_name='medical',
            name='medical_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
