# Generated by Django 2.1.3 on 2018-11-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20181108_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet_name',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user.mypet'),
        ),
    ]
