# Generated by Django 2.0.7 on 2018-11-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20181127_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
