# Generated by Django 2.0.7 on 2018-11-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20181128_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='age',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='age',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
