# Generated by Django 2.1.3 on 2018-11-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20181129_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queue',
            name='pet_name',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user.mypet'),
        ),
    ]
